### ISSUE TITLE
How to send to mutiple device tokens?

### ISSUE THREAD

**Issue by erhuabushuo** [Fatal1ty/aioapns#1]
How to send to mutiple device tokens?

**Comment by Fatal1ty** [comment]
@erhuabushuo APNs doesn't have possibility to set multiple device tokens for one notification, so you can send notifications to multiple recipients in a cycle for example. But I recommend you sending notifications in parallel using _asyncio.wait_ method. It just depends on you and your tasks.

**Comment by Fatal1ty** [comment]
You can find code sample with parallel sending of notifications here https://github.com/Fatal1ty/aioapns/blob/master/examples/client.py#L33:L46
