### ISSUE TITLE
Please support apns-push-type header field requirement

### ISSUE THREAD

**Issue by fritzt0** [Fatal1ty/aioapns#12]
Many thanks for your python module, I like the compact, well-designed API. For the new watchOS 6, Apple changed the requirements to now require a new header field 'apns-push-type' in order to be delivered to watchOS. It would be nice to have support for watchOS devices in aioapns. The new requirements are described in: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns#2947607
Again, many thanks!

**Comment by Fatal1ty** [comment]
Hello. Thank you for the idea. It doesn’t seem very difficult. I’ll support this header field soon.

**Comment by Fatal1ty** [comment]
Added in 1.9
