### ISSUE TITLE
ValueError when no_cert_validation=True

### ISSUE THREAD

**Issue by decaz** [Fatal1ty/aioapns#18]
https://github.com/Fatal1ty/aioapns/blob/0d6f02c32b31535d8cc3983b36c879cf3b254074/aioapns/connection.py#L412-L414
With CPython 3.8.5 this gives `ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.`.

If these settings are swapped, then the error doesn't occur.

**Comment by Fatal1ty** [comment]
Fixed in 1.12
