### ISSUE TITLE
apps-id hader not exists in response

### ISSUE THREAD

**Issue by NotSoSmartDev** [Fatal1ty/aioapns#19]
When I trying to send notification, lib starts spawning an error:

```
Traceback (most recent call last):
  File "/Users/dmitrijsenuk/.pyenv/versions/3.7.4/lib/python3.7/asyncio/sslproto.py", line 545, in data_received
    self._app_protocol.data_received(chunk)
  File "/Users/dmitrijsenuk/Projects/subscriptions_api/venv/lib/python3.7/site-packages/aioapns/connection.py", line 85, in data_received
    self.on_response_received(headers)
  File "/Users/dmitrijsenuk/Projects/subscriptions_api/venv/lib/python3.7/site-packages/aioapns/connection.py", line 229, in on_response_received
    notification_id = headers.get(b'apns-id').decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'
Could not send notification ea9416a1-e7cb-476c-af10-cc20d5b054f0: ConnectionClosed
application protocol failed to receive SSL data
protocol: <asyncio.sslproto.SSLProtocol object at 0x11dbcad50>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
```

In the same time device continue receive same notification until I press ctrl-C.

**Comment by NotSoSmartDev** [comment]
As I figure out problem is in headers no b'apns-id', only 'apns-id'. Cloud it be incompatibility on any of libraries?

**Comment by Fatal1ty** [comment]
Hello! For understanding this problem, could you tell me whether you provided an invalid `notification_id` in `NotificationRequest` object? It would be helpful if you provided more information such as your request and response from the server.

**Comment by NotSoSmartDev** [comment]
Sorry for this issue, it was my unknown problem. After restart console everything starts work fine. Thank you a lot for a great library!

**Comment by fflisguhcz04697** [comment]
I also encounter this problem, i print out the response, it is 'apns-id' not b'apns-id', after debugging one or two hours. The problem suddenly solved, and i print the response, it changed to b'apns-id'.
I wonder can the lib provide a flag to control at most send once even encounter an error, \if the above scene appear in product env, server will send thousands notifications to user, this is a disaster.
