### ISSUE TITLE
JWT Token re-generated on every notification

### ISSUE THREAD

**Issue by davidattias** [Fatal1ty/aioapns#35]
I can see in the code that you re-generate a JWT token every time a notification is sent.

In the docs from Apple, it is said that :
`APNs reports an error if you recreate your tokens more than once every 20 minutes`
cf https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

Don't you have issues while using this library on production due to this constraint?

**Comment by Fatal1ty** [comment]
Hi @davidattias 

> Don't you have issues while using this library on production due to this constraint?

Unfortunately, I can't check it because of my new job where I no longer have access to the Apple developer program. This stops me from maintaining this project at the moment.

**Comment by davidattias** [comment]
OK thanks @Fatal1ty

**Comment by alexmv** [comment]
The [JWT token is cached](https://github.com/Fatal1ty/aioapns/blob/10757c1efa69713d0fd7d29fe600032c434168de/aioapns/connection.py#L71) for `TOKEN_TTL` seconds, which defaults to [30 minutes](https://github.com/Fatal1ty/aioapns/blob/10757c1efa69713d0fd7d29fe600032c434168de/aioapns/connection.py#L59).

**Comment by Fatal1ty** [comment]
> The [JWT token is cached](https://github.com/Fatal1ty/aioapns/blob/10757c1efa69713d0fd7d29fe600032c434168de/aioapns/connection.py#L71) for `TOKEN_TTL` seconds, which defaults to [30 minutes](https://github.com/Fatal1ty/aioapns/blob/10757c1efa69713d0fd7d29fe600032c434168de/aioapns/connection.py#L59).

@alexmv thank you for pointing out to this! We certainly don't generate a new JWT token on every request. I think I can close this issue as irrelevant.
