### ISSUE TITLE
Is there a way to reuse the connection?

### ISSUE THREAD

**Issue by oculos** [Fatal1ty/aioapns#49]
Hi,

Apple recommends to reuse the connection when sending a lot of messages. Is there a way to do so here?

**Comment by Fatal1ty** [comment]
This library has APNs client that holds a smart connection pool that creates a new connection only if existing connections can't handle your working load. Each connection in this pool can handle 1000 asynchronous notification requests.

**Comment by oculos** [comment]
> This library has APNs client that holds a smart connection pool that creates a new connection only if existing connections can't handle your working load. Each connection in this pool can handle 1000 asynchronous notification requests.

Thanks a lot.

Following your example, I see that the client instantiation occurs inside the `run()` function. If I want to send multiple requests, should I create the client outside the `run()` function, or it doesn't matter?

**Comment by Fatal1ty** [comment]
> Following your example, I see that the client instantiation occurs inside the run() function. If I want to send multiple requests, should I create the client outside the run() function, or it doesn't matter?

In the example it doesn't really matter. You only need to create and reuse one instance of the client in your application / script. It's preferred to create the client after creating an event loop, so it would be safer to do it inside a coroutine function, as in the example.

**Comment by oculos** [comment]
Thank you. 
My point is, if I want to send multiple messages at once and multiple messages throughout the day, I thought that I’d do it like this:

- start the event loop
- create the client outside a function, so it can be reused
- call the run function

Does it work this way?

**Comment by Fatal1ty** [comment]
> Does it work this way?

Yes, it should work that way.
