### ISSUE TITLE
Getting 400 (BadDeviceToken)

### ISSUE THREAD

**Issue by emptycrown** [Fatal1ty/aioapns#53]
I'm getting a `400 (BadDeviceToken)` error when running the example code using a .p8 certificate. How do I correctly get the device token?

**Comment by zt50tz** [comment]
How you solved this? Thanks.

**Comment by emptycrown** [comment]
Yes, it was an issue with the `use_sandbox` param

**Comment by zt50tz** [comment]
Thanks!
And my problem was in incorrect token of device.
