### ISSUE TITLE
Version 3.3 breaks connection

### ISSUE THREAD

**Issue by aalbinati** [Fatal1ty/aioapns#67]
My server is no longer sending notifications after the release.

<img width="801" alt="image" src="https://github.com/Fatal1ty/aioapns/assets/66640950/c3da6c0f-02b8-4e6c-b494-00e88131b051">

The exception source is line 377 from the connection.py file, it seems create_connection(self) is not implemented yet.

If you need more info I can provide it. Maybe #66 can fix this error.

**Comment by Fatal1ty** [comment]
Fixed in 3.3.1

**Comment by aalbinati** [comment]
Testing it as we speak

**Comment by aalbinati** [comment]
3.3.1 Is now working as expected. Thx!
